# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-26 17:32:10
"""
# Set environment to prevent overwriting existing outputs
import arcpy

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Fire_Disturbance_A_Intersect = "Fire_Disturbance_A_Intersect"
    Fishing_Access_Point = "Fishing_Access_Point"

    # Process: Create buffer around fishing access points
    Fishing_Access_Point_Buffer = "C:\\Users\\jamim\\OneDrive\\Documents\\ArcGIS\\Projects\\week9-programing\\week9-programing.gdb\\Fishing_Access_Point_Buffer"
    arcpy.analysis.Buffer(in_features=Fishing_Access_Point, out_feature_class=Fishing_Access_Point_Buffer, buffer_distance_or_field="1 Kilometers", dissolve_option="ALL", method="PLANAR")

    # Process: Intersect fire disturbance data with buffered fishing access points
    Fire_Disturbance_A_Intersect1 = "C:\\Users\\jamim\\OneDrive\\Documents\\ArcGIS\\Projects\\week9-programing\\week9-programing.gdb\\Fire_Disturbance_A_Intersect1"
    arcpy.analysis.Intersect(in_features=[[Fire_Disturbance_A_Intersect, ""], [Fishing_Access_Point_Buffer, ""]], out_feature_class=Fire_Disturbance_A_Intersect1)

# Step 3: Clip the intersect result to a specific area of interest
    # Define the output pasth for the clipped data
    clipped_output = "C:\\Users\\jamim\\OneDrive\\Documents\\ArcGIS\\Projects\\week9-programing\\week9-programing.gdb\\clipped_output"# Step 3: Clip the intersect result to a specific area of interest
   
if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\jamim\\OneDrive\\Documents\\ArcGIS\\Projects\\week9-programing\\week9-programing.gdb", workspace="C:\\Users\\jamim\\OneDrive\\Documents\\ArcGIS\\Projects\\week9-programing\\week9-programing.gdb"):
        Model()
       